(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.text2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#215474").s().p("AhWByQgJgCgJgFQgIgFgGgJQgGgHAAgMIAkAAQADAKAHAEQAHAEAKAAQAPAAAHgJQAIgKgBgNIAAgSIAAAAQgGAKgLAFQgKAGgNgBQgQABgJgGQgMgEgGgKQgEgFgDgGIgBgFIgDgGQgDgLAAgNQABgOADgLQAEgMAHgJQAHgJALgFQAMgGAMAAQAMAAALAFQALAGAGALIAAAAIAAgSIAiAAIAAB7QAAAHgCALQgBALgIAJQgHAIgOAGQgNAHgXgBQgJAAgLgCgAhMgmQgHAFgCADQgEAHgCAFQgCAGAAAJQABAGABAGQACAIADAGIAEAEIAFAFQAGADAIAAQAIAAAGgDIABAAIAGgFIACgDQAFgFACgHQABgGAAgGQAAgJgBgHQgCgHgEgGQgDgGgGgDQgHgEgIAAQgIAAgFAEgAGTBBQgMgFgJgJQgJgIgFgOQgFgOAAgPQAAgOAFgNQAFgOAJgJQAJgJAMgFQAOgFAOAAQAPAAAOAFQAMAFAKAJQAJAKAFANQAEALAAAQQAAARgEAMQgFAMgJAKQgKAJgMAFQgOAFgPAAQgOAAgOgFgAGhglQgHADgDAGQgFAHgBAGQgCAIABAHQgBAIACAIQABAHAFAGQADAHAHADQAFADAJABQAKgBAGgDQAHgEADgGQAEgGACgHIABgQQAAgHgBgIQgCgGgEgHQgDgFgHgEQgHgFgJAAQgIAAgGAFgAjuBBQgMgFgJgJQgHgIgGgLIgBgDIgBgCQgEgNAAgOQAAgOAFgNQAFgOAJgJQAKgJALgFQAOgFAOAAQAPAAAOAFQAMAFAKAJQAJAKAEANQAGALAAAQQgBAQgEALIgBACIgBADQgEAKgIAJQgJAJgNAFQgOAFgPAAQgOAAgOgFgAjhglQgFADgFAGQgEAHgBAGQgBAIAAAHIABAQQABAGADAFIABACIACADQADAEAFADQAGADAJABQALgBAFgDQAGgDADgEIABgDIABgCIAFgLIABgQQAAgHgBgIQgCgGgEgHQgCgFgIgEQgGgFgKAAQgIAAgHAFgAl6BBQgMgFgJgJQgIgIgEgLIgBgDIgBgCQgEgMgBgNQABgOAEgOQAEgNAJgJQAJgKAMgFQAOgGAQAAQAMAAAKAEQALACAIAHQAJAHAGAIQAEAKABANIgjAAQgEgYgXAAQgIAAgGAFQgHAEgDAGQgEAGgCAIIgBAOIABAPQABAFAEAGIABACIABADQADAEAFACQAGAFAIAAQANAAAIgIIADgDIACgFQADgFABgGIAjAAIgDALIgBAFQgGAPgLAJQgSAOgaAAQgNAAgOgFgAoHBBQgNgFgJgJQgHgJgFgKIgBgEIAAgBQgFgMAAgPQAAgOAFgNQAFgNAIgIQAJgLANgEQAOgGAOAAQAQAAANAHQANAGAHALQAIALAFAPQADAMgBAQIhgAAQABALAEAHIACAFIACADQAIAHAQABQAKgBAJgFIAHgFIACgFIAAgBIAhAAIgBABIgCAFQgGASgPAKQgQAKgWAAQgPAAgNgFgAn7gmQgGADgDAEQgEAEgBAFIgCAJIA8AAQgDgOgGgHQgHgIgNAAQgJAAgGAEgAEGBCQgHAAgHgEQgFgDgEgGQgDgGAAgLIAAhNIgWAAIAAgYIAWAAIAAgoIAlAAIAAAoIAaAAIAAAYIgaAAIAABBQAAAJACADQADADAKAAIAFAAIAGgBIAAAcIgVACIgQgCgAJdBCIAAhKQAAgPgGgJQgFgIgNAAQgPAAgGAJQgHAIAAAVIAABEIgkAAIAAiDIAiAAIAAATIABAAQAHgMALgFQAMgGAKAAQAOAAAKAEQAKAFAFAGQAGAHABALQADALAAALIAABQgAE2BCIAAiDIAkAAIAACDgACpBCIAAiDIAkAAIAACDgABwBCIAAhKQgBgPgFgJQgFgIgNAAQgPAAgGAJQgHAIAAAVIAABEIglAAIAAiDIAjAAIAAATIABAAQAGgMALgFQANgGALAAQANAAAKAEQAKAFAFAGQAGAHACALQACALAAALIAABQgAqABCIAAiDIAiAAIAAAYIABAAQACgGAFgFQAFgGAFgDQAGgEAGgBQAGgDAIAAIAHABIAAAiIgNgBQgKAAgHADQgHAEgEAFQgFAHgBAHQgCAJAAAHIAAA7gAE2hWIAAgeIAkAAIAAAegACphWIAAgeIAkAAIAAAeg");
	this.shape.setTransform(-94.9329,2.1118,1.0667,1.0667);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#215474").s().p("ADKByQgKgCgJgGQgHgEgHgJQgFgIgBgLIAkAAQADALAHADQAHAEALAAQAPAAAHgJQAHgIAAgQIAAgRIgBAAQgGAMgLAEQgKAEgNABQgPgBgKgEQgLgGgHgJQgGgJgEgMQgDgMAAgNQAAgMAEgNQACgKAIgLQAHgIALgHQAKgEAPAAQANAAAKAEQAKAFAGALIABAAIAAgRIAiAAIAAB7QAAAJgCAJQgCALgHAIQgHAJgOAHQgOAFgWABQgJAAgLgDgADTgmQgFADgEAFQgEAGgBAHIgCANQAAAHACAHIAEAMQAFAHAFACQAFAEAJAAQAHAAAGgDQAGgDAEgFQAEgGACgFQACgGAAgIQAAgHgCgIQgBgFgEgIQgEgGgFgDQgGgDgJAAQgIAAgGADgAFBBwIgMAAIAAgeIAWABQAGAAAEgGQAEgFAAgFIgCgJIguh7IAnAAIAeBZIAAAAIAdhZIAmAAIg4CUQgGARgKAGQgLAHgSAAIgLgBgAAyBBQgMgFgKgJQgJgKgEgMQgFgMAAgQQAAgRAFgMQAEgLAJgLQAKgJAMgFQAMgEAQAAQARAAAMAEQALAFAKAJQAJAJAFANQAFANAAAQQAAAPgFANQgFANgJAJQgKAKgLAEQgOAFgPAAQgOAAgOgFgAA/gmQgHAEgDAGQgEAFgBAJIgCAPQAAAHACAIQABAIAEAGQADAFAHAEQAFAEAKgBQAKABAGgEQAGgEAEgFQAEgHABgHQACgIAAgHIgCgPQgBgIgEgGQgEgGgGgEQgGgDgKAAQgKAAgFADgAicBBQgNgFgJgJQgJgJgFgNQgFgMAAgQQAAgRAFgMQAFgMAJgKQAJgJANgFQALgEARAAQAQAAAMAEQAMAFAKAJQAIAJAGANQAEANAAAQQAAAPgEANQgGANgIAJQgKAKgMAEQgOAFgOAAQgPAAgNgFgAiQgmQgGAEgEAGQgEAHgBAHIgBAPQAAAHABAIQABAGAEAIQAEAFAGAEQAGAEAKgBQAKABAFgEQAHgEADgFQADgFADgJQABgIAAgHIgBgPQgDgKgDgEQgDgGgHgEQgFgDgKAAQgKAAgGADgApJBBQgNgFgJgJQgIgJgFgMQgFgPAAgNQAAgOAEgNQAFgOAJgKQAHgIAOgHQAMgEARAAQAMAAAKACQAMADAIAHQAJAGAFAJQAFAJABANIgkAAQgDgWgYAAQgJAAgFAEQgGAEgEAGQgEAGgBAIIgCAOIACAOQABAHAEAHQAEAHAFADQAGAEAJgBQANAAAHgGQAHgIACgMIAjAAQgEAbgRANQgRAOgaAAQgOAAgNgFgArXBBQgNgFgJgKQgJgIgEgNQgFgNAAgPQAAgOAFgNQAFgOAJgJQAIgIANgHQAMgEAQAAQARAAAMAGQANAGAIAMQAIALAEANQADANgBAQIhgAAQACASAHAHQAIAIAQAAQAMABAHgGQAIgFACgHIAgAAQgIAYgQAKQgPALgXAAQgPAAgNgFgArLgnQgGADgDAFQgDAEgCAFIgCAJIA8AAQgCgMgHgJQgHgHgNAAQgIAAgHACgAsoBDQgIgCgFgDQgGgDgDgHQgDgGAAgJIAAhOIgWAAIAAgYIAWAAIAAgoIAkAAIAAAoIAbAAIAAAYIgbAAIAABBQAAAJADAEQADACAJAAIAMAAIAAAcIgWABQgIAAgIgBgAM0BDIAAi2IAkAAIAAC2gAL6BDIAAi2IAkAAIAAC2gAK/BDIAAiEIAlAAIAACEgAJnBDIgXhZIgBAAIgXBZIglAAIgqiEIAmAAIAYBZIABAAIAWhZIAjAAIAXBYIABAAIAYhYIAlAAIgpCEgAgrBDIAAi2IAlAAIAAC2gAj5BDIAAhKQAAgRgFgIQgGgIgMAAQgQAAgGAJQgHAJAAAUIAABFIgkAAIAAiEIAjAAIAAASIAAAAQAHgLALgGQALgEAMAAQAQAAAIADQAKAFAFAHQAFAGACAKQACAKAAANIAABRgAmJBDIAAhKQAAgRgGgIQgFgIgNAAQgOAAgHAJQgHAJAAAUIAABFIgkAAIAAi2IAkAAIAABEIABAAQAGgLALgGQALgEAKAAQAQAAAIADQAKAFAFAHQAFAGADAKQACAKAAANIAABRgAK/hWIAAgdIAlAAIAAAdg");
	this.shape_1.setTransform(72.1201,2.419,1.0667,1.0667);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#215474").s().p("AsqByIAAgeIAKABIALAAQAIgBACgFQAEgEAAgGQAAgFgBgEIgvh7IAnAAIAeBaIAAAAIAdhaIAmAAIg4CUQgGAQgJAHQgLAHgTAAgALSBCQgLgGgIgKQgHgLgDgLQgEgMAAgPQAAgNAEgMQADgKAHgMQAJgKAKgFQAMgGAOAAQAMAAAKAFQALAGAGAJIAAAAIAAhDIAlAAIAAC3IgjAAIAAgRIAAAAQgHAKgKAFQgLAFgNAAQgOAAgMgGgALmgkQgFAEgFAGQgEAGgBAHQgBAIAAAHIABAPQACAIAEAGQAEAGAGAEQAHAEAHAAQAJAAAHgEQAFgDAEgHQAEgFABgIQACgIAAgIQAAgHgCgIQgBgIgEgFQgEgGgFgEQgGgDgKAAQgJAAgGADgAJBBGQgIgDgHgFQgGgFgDgHQgDgHAAgLQgBgMAEgGQAFgIAGgEQAGgDAIgCIARgEIAQgCIANgCQAHgCADgDQAEgDAAgFQAAgGgCgEQgCgCgEgDQgDgCgEgBIgJAAQgLAAgGAEQgGAFgBALIglAAQACgNAFgJQAFgIAKgFQAIgFALgDIAWgCIAUACQAJABAKAEQAIAEAFAIQAGAHAAAMIABBVQACAJABAEIgkAAIgCgHIgBgGQgIAIgMAEQgLAEgNAAQgLAAgHgCgAJ4AHIgQADIgJABIgHACIgHAEIgGAFQgBAEAAAFQAAAFABADIAGAFIAHADIAIABQALAAAGgEQAFgDADgFQADgFABgGIABgVIgGADgAG6BDQgNgFgIgJQgKgKgEgMQgFgMAAgRQAAgPAFgNQAEgMAKgKQAHgIAOgGQAMgFAQAAQARAAAMAFQANAGAJAIQAIAKAFAMQAFAOAAAOQAAARgFAMQgFANgIAJQgJAJgNAFQgMAFgRAAQgQAAgMgFgAHHgkQgGAEgEAGQgDAGgCAIQgBAHAAAHQAAAIABAIQACAIADAFQAEAGAGAEQAHAEAIAAQAIAAAIgEQAGgEAEgGQAEgFABgIQABgIABgIQgBgHgBgHQgBgIgEgGQgEgGgGgEQgIgDgIAAQgIAAgHADgAADBDQgLgFgJgJQgJgJgGgNQgEgMAAgRQAAgOAEgOQAGgMAJgKQAJgIALgGQAMgFAQAAQARAAAMAFQANAGAIAIQAKAKAEAMQAFANAAAPQAAARgFAMQgEAMgKAKQgJAJgMAFQgMAFgRAAQgQAAgMgFgAAQgkQgGAEgEAGQgDAGgCAIQgBAGAAAIQAAAJABAHQACAIADAFQAEAGAGAEQAHAEAIAAQAIAAAIgEQAGgEAEgGQADgFACgIQABgIABgIQgBgHgBgHQgCgIgDgGQgEgGgGgEQgIgDgIAAQgIAAgHADgAn9BEQgKgFgEgGQgGgHgCgKQgCgLAAgMIAAhQIAkAAIAABKQAAAQAFAIQAFAIANAAQAPAAAHgIQAHgJgBgVIAAhEIAlAAIAACEIgiAAIAAgTIgCAAQgGALgLAGQgLAFgMAAQgPAAgJgEgAqGBDQgNgFgIgJQgLgLgEgLQgEgMAAgRQAAgPAEgNQAEgLALgLQAIgIANgGQALgFARAAQAQAAAMAFQAOAGAIAIQAJAKAFAMQAFAPAAANQAAAPgFAOQgFANgJAJQgJAJgNAFQgMAFgQAAQgRAAgLgFgAp6gkQgFAEgEAGQgEAHgBAHQgCAHAAAHQAAAIACAIQABAHAEAGQAEAHAFADQAIAEAIAAQAIAAAIgEQAFgDAFgHQADgGACgHQABgIABgIQgBgHgBgHQgCgHgDgHQgFgHgFgDQgIgDgIAAQgIAAgIADgAFdBFIAAi3IAkAAIAAC3gAEqBFIgkg8IgOAOIAAAuIglAAIAAi3IAlAAIAABjIAugwIArAAIgyAxIA4BTgAB0BFIAAiEIAjAAIAAAZIAAAAQADgHAEgFQAFgGAFgDIAMgGQAGgCAHAAIAIACIAAAhIgMgBQgLAAgHAEQgGACgFAHQgDAFgDAIQgCAHABAJIAAA8gAh3BFIgYhYIAAAAIgXBYIgmAAIgpiEIAmAAIAZBZIAAAAIAWhZIAkAAIAWBZIABAAIAYhZIAlAAIgpCEgAmFBFIAAiEIAjAAIAAAZIABAAQABgFAFgHQAEgFAGgEQAGgEAHgCQAFgCAHAAIAIACIAAAhIgMgBQgLAAgGAEQgIADgDAGQgFAFgBAIQgCAHAAAJIAAA8g");
	this.shape_2.setTransform(63.5848,30.6377,1.0667,1.0667);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#215474").s().p("ACZBYQgLgEgKgKQgJgJgFgNQgFgOAAgOQAAgOAFgOQAFgOAJgIQAJgJAMgFQAMgFAQAAQARAAAMAFQANAFAIAJQAJAIAFAOQAFAOAAAOQAAAOgFAOQgFANgJAJQgKAKgLAEQgMAFgRAAQgQAAgMgFgACmgOQgFADgFAGQgEAGgBAHQgCAIAAAIQAAAIACAHQABAHAEAHQAFAHAFACQAHAEAIAAQAJAAAHgEQAFgCAFgHQAEgHABgHQACgHAAgIQAAgIgCgIQgBgHgEgGQgFgGgFgDQgGgEgKAAQgJAAgGAEgAg4BbQgLgCgJgGQgHgEgHgKQgFgJgBgNIAiAAQAAAGADAEQADAFADACIAJAEQAFABAFAAIAIgBQAEAAAEgDQADgBADgEQACgDAAgFQAAgIgLgEQgNgFgRgDIgQgFQgHgCgGgEQgHgGgDgEQgDgHAAgHQAAgMAFgJQAFgIAIgFQAKgFAJgBQAIgCANAAQALAAAKACQALACAGAFQAHAEAGAJQAFAIABAMIgiAAQgBgLgHgDQgGgEgKAAIgHAAIgHACIgFAEQgCACAAAEQAAAFAEADQAFADAEABIAsALQAIAEAFADQAFAEAEAHQAEAIAAAHQAAANgGAJQgFAJgIAFQgHAGgMACQgJACgNAAQgLAAgLgCgAlgBbQgIgCgGgFQgHgGgDgHQgDgHAAgKQAAgMAEgHQADgHAHgFQAJgFAFgBIAvgIQAGgBAEgDQADgEAAgEQAAgHgCgCQgBgDgEgDQgCgBgGgBIgJgBQgLAAgGAFQgGAEgBALIgkAAQABgNAFgIQAFgIAKgGQAIgFALgCQAKgCAMAAIAUABQALACAIAEQAIADAGAIQAFAGAAANIABBWQACAJACADIglAAIgDgNQgIAJgMAEQgLADgNAAQgJAAgJgCgAkpAcIgHACIgRADIgIACIgHADIgFAGQgCADAAAFQAAAFACADIAFAGIAHACIAIABQAKAAAHgDQAGgEADgFQACgEABgGIABgWgAoBBaQgHgBgGgDQgGgEgDgGQgEgGAAgKIAAhNIgWAAIAAgZIAWAAIAAgnIAlAAIAAAnIAaAAIAAAZIgaAAIAABAQAAAKADADQADADAJAAIALgBIAAAcIgVABIgQgBgAINBaIAAhYQgBgGgCgDQgDgFgEgCQgFgDgHAAQgIAAgEADQgGADgCAFQgCAEgBAGIgBAMIAABKIglAAIAAhWQAAgGgCgEQgCgFgFgDQgEgDgJAAIgHACQgEABgEADQgEAEgDAFQgCAEAAALIAABNIglAAIAAiEIAiAAIAAASIABAAQAGgJALgHQALgFANAAQANAAAJAFQALAEAFANQAGgIAKgIQAKgGAOAAQAKAAAKACQAHACAIAGQAHAHADAIQAEAJAAAMIAABZgAEKBaIAAiEIAjAAIAAAZIAAAAQACgFAFgHQAEgEAGgEIAMgGQAGgCAHAAIAIABIAAAiIgGgBIgHAAQgJAAgIADQgGADgFAFQgEAGgCAHIgCARIAAA8gAAvBaIAAhrIgWAAIAAgZIAWAAIAAgKQAAgSALgLQAMgLAWAAIAJAAIAKABIAAAbIgOgBQgHAAgDAEQgDADAAAIIAAAIIAZAAIAAAZIgZAAIAABrgAiSBaIAAhLQAAgQgFgIQgGgIgNAAQgOAAgHAJQgHAIAAAUIAABGIgkAAIAAiEIAiAAIAAATIABAAQAHgMALgFQALgFAMAAQANAAALAEQAJADAFAIQAGAGACALQACANAAAIIAABSgAnSBaIAAiEIAjAAIAAAZIAAAAIAHgMIAKgIIAMgGQAGgCAIAAIAIABIAAAiIgHgBIgGAAQgKAAgHADQgHADgFAFQgDAGgDAHIgBARIAAA8g");
	this.shape_3.setTransform(-91.2799,28.6198,1.0667,1.0667);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#215474").s().p("AkVBzIAAiyIAjAAIAAAQIABAAQAFgJALgGQAMgFALAAQAQAAALAGQALAFAIALQAHAJAEANQADAMAAAOQAAAPgDALQgEAMgHAKQgIAKgKAFQgLAGgPAAQgLAAgMgFQgKgFgHgKIAAAAIAAA/gAjhgkQgGAEgEAGQgDAFgCAIQgBAIAAAHQAAAIABAIQACAIAEAFQADAGAGAEQAHADAIAAQAKAAAFgDQAHgEADgGQAEgFABgIQACgIAAgIQAAgHgCgHQgBgIgEgGQgEgGgGgEQgHgEgIAAQgIAAgHAEgAC6BDQgMgFgJgJQgIgJgGgNQgFgOAAgNQAAgPAFgNQAEgNAJgKQAIgJANgGQAOgFAPAAQANAAAKADQALADAIAGQAJAHAFAJQAFAJABANIgjAAQgEgXgXAAQgIAAgHAEQgGAFgDAGQgEAGgCAIIgBAOIABAOQABAGAEAIQAEAGAGADQAFAEAJAAQANAAAHgHQAHgHACgNIAjAAQgDAagRAPQgSAOgaAAQgNAAgOgFgAAsBDQgMgFgJgKQgJgJgFgNQgEgMAAgQQAAgOAEgNQAGgNAIgJQAJgKANgFQAMgFAPAAQARAAANAHQANAGAHALQAIALAEAOQADAPAAAOIhgAAQABASAIAHQAIAIAQAAQAKAAAJgFQAIgGABgGIAgAAQgHAXgQALQgQALgXAAQgOAAgOgFgAA5glQgGADgDAFQgEAEgBAFIgCAJIA7AAQgCgNgHgIQgGgIgOAAQgIAAgGADgAheBDQgMgFgKgKQgJgJgEgNQgFgMAAgQQAAgOAFgNQAFgNAJgJQAJgKAMgFQANgFAPAAQAQAAANAHQANAGAIALQAIALAEAOQADAPgBAOIhgAAQABASAIAHQAIAIAQAAQALAAAIgFQAIgGACgGIAgAAQgHAXgRALQgPALgXAAQgPAAgNgFgAhSglQgFADgEAFIgFAJIgCAJIA8AAQgDgOgGgHQgHgIgNAAQgJAAgGADgAl1BFQgMgCgIgGQgIgFgGgJQgFgJgBgNIAjAAQAAAHACADQACAEAEADIAJAEIALABIAIAAIAHgDIAGgFQACgEAAgFQAAgIgLgEQgIgDgWgFIgPgEQgGgCgIgEQgFgDgEgHQgEgFAAgJQAAgOAFgHQAFgJAIgEQAHgFAMgCIAVgCQAJAAAMACQAIACAKAFQAHAEAGAJQAGAJAAALIgiAAQgBgKgHgEQgIgEgJAAIgHABIgGABIgGAEQgCADAAAEQAAAFAEADQACACAHADIAsALQAHACAHAEQAFADAEAHQAEAGAAAKQAAANgFAJQgGAIgIAGQgIAFgMACQgLADgLAAQgKAAgMgDgAF6BEIAAhKQAAgQgFgIQgFgIgNAAQgPAAgHAJQgHAIAAAVIAABEIgkAAIAAi2IAkAAIAABFIABAAQAHgLALgGQAMgFAJAAQAOAAAKAEQAKAEAFAHQAFAHACAKQACAJAAAOIAABQg");
	this.shape_4.setTransform(128.0657,-27.7241,1.0667,1.0667);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#215474").s().p("AxYBYQgSgIgKgMQgNgMgFgSQgHgRAAgUQAAgUAHgRQAFgSANgNQAKgNASgIQASgHATAAQAPAAAOAEQANAFALAIQAKAHAIAOQAHAMACAQIgoAAQAAgHgEgGQgDgFgGgFQgFgFgHgCQgJgCgGAAQgNAAgKAFQgJAFgGAJQgFAIgDAMQgDAKAAANQAAANADAJQADANAFAHQAGAJAJAFQAKAFANAAQATAAAKgLQALgLACgTIAnAAQgCASgGANQgGANgLALQgLAKgOAFQgQAFgPAAQgUAAgRgIgAPyBdQgHgCgIgGQgFgEgEgIQgEgIABgKQAAgKADgIQAFgIAGgEQAFgEAKgCQAKgDAGgBIAPgCIAPgCQAGgCADgDQAEgDAAgEQAAgFgCgFIgFgFIgHgDIgJAAQgMAAgGAEQgFAEgCALIglAAQACgMAFgJQAHgIAHgFQAKgGAKgBQANgDAJAAIAUACQAKABAJAEQAKAGAEAGQAGAIAAALIAABEIABARQAAAJADAEIglAAIgCgNQgJAJgMADQgLAEgNAAQgLAAgHgCgAQpAeIgHACIgSACIgIACIgHAEQgCACgCADQgCAEAAAFQAAAFACADQACAEACABIAIADIAIABQALAAAGgEQAFgDAEgFQADgHAAgEIABgIIAAgNQgCACgEABgAN1BaQgMgEgKgKQgJgJgEgNQgFgNgBgOQAAgPAFgMQAFgNAIgKQAJgJANgGQANgGAQAAQAMAAAKADQAKADAKAHQAIAFAFAKQAGAKABAMIgkAAQgDgWgYAAQgIAAgHAEQgFADgEAHQgEAGgBAHQgCAHAAAIQAAAHACAIQABAFADAIQAEAGAGAEQAGAEAJAAQANAAAGgIQAHgGACgNIAkAAQgEAagRAOQgRAOgaAAQgQAAgLgFgAGpBaQgMgEgKgKQgIgJgFgNQgFgMAAgPQAAgPAFgMQAEgNAJgKQAJgKANgFQAMgGAQAAQAMAAAKADQAKADAKAHQAIAFAGAKQAGAKABAMIgkAAQgDgWgYAAQgJAAgGAEQgGADgEAHQgDAEgCAJIgCAPIACAPIAFANQAEAGAFAEQAHAEAIAAQAOAAAGgIQAHgGACgNIAjAAQgEAagQAOQgRAOgbAAQgQAAgLgFgADMBZQgMgGgGgKQgHgJgEgNQgEgOAAgNQAAgMAEgNQAEgNAHgJQAHgJALgGQALgGAPAAQAKAAANAFQAKAGAGAJIAAAAIAAhDIAlAAIAAC3IgiAAIAAgRIgBAAQgGAKgLAFQgLAFgNAAQgOAAgMgGgADggNQgGAEgEAGQgDADgCAJQgBAIAAAIQAAAIACAIQABAHAEAGQAEAHAGADQAHAEAHAAQAKAAAGgEQAGgEADgGQAEgGABgHQACgIAAgIQAAgIgCgIQgBgHgEgFQgEgGgFgEQgIgDgIAAQgHAAgIADgABGBaQgLgEgKgKQgJgKgFgMQgEgNAAgQQAAgOAEgMQAGgNAJgKQAJgJAMgFQAMgGAPAAQAQAAAOAHQANAHAHAKQAJAMADANQAEAPgBAOIhgAAQABASAIAIQAIAIAQAAQALAAAIgGQAIgFACgGIAfAAQgHAXgQALQgQAKgXAAQgQAAgMgFgABTgNQgFADgEAEQgDADgCAFIgCAJIA8AAQgDgMgGgIQgIgHgNAAQgIAAgGADgAg6BdQgLgCgJgGQgJgFgFgJQgFgJgCgOIAjAAQAAAHADAEIAGAHQAFADAEAAIAKACIAIgBIAIgDQAEgCACgDQACgDAAgFQAAgIgKgEQgJgEgWgFIgPgEIgOgGQgFgEgFgGQgDgGAAgIQAAgNAFgIQAEgHAJgGQAIgEALgDQAJgCALAAIAWACQAIACAJAFQAIAFAFAIQAFAJABAMIghAAQgBgLgIgEQgHgDgKAAIgGAAQgDAAgDACIgGADQgCAEAAADQAAAFAEACQACADAHACIAOADIAOAEQAIABAIADQAFACAIAFQAFAEAEAGQADAHAAAJQAAAOgEAIQgGAJgIAFQgIAFgKADQgLACgMAAQgMAAgKgCgAjSBdQgIgDgGgFQgFgEgFgIQgDgHAAgLQAAgKAEgIQADgHAHgFQAHgEAHgCIARgEIAQgCIAOgCQAGgCAEgDQAEgDgBgEQAAgGgBgEIgGgFQgDgCgFgBIgJAAQgKAAgHAEQgFAFgBAKIglAAQABgMAFgJQAHgIAIgFQAJgGAKgBQANgDAJAAIAVACQAJABAKAEQAIAFAFAHQAFAHABAMIAABVQACAJACAEIglAAIgCgHIAAgGQgJAIgMAEQgLAEgNAAQgKAAgIgCgAibAeIgQADIgIABIgIACIgHAEIgFAFQgBAEgBAFQABAFABADIAFAFIAHADIAJABQALAAAFgEQAGgDADgFQADgFABgGIAAgVQgDACgDABgAlIBaQgLgEgGgLIgBAAIAAARIgjAAIAAi3IAlAAIAABDIAAAAQAHgKALgFQALgFAOAAQAJAAAKAEQALAFAGAIQAIAIAFAOQAFAMAAASQAAASgFAOQgFAOgIAHQgIAJgJAEQgIAEgLAAQgPAAgMgFgAlIgNQgGAEgEAGQgEAFgCAHIgBAQIABAQQACAHAEAHQAEAFAGAEQAFAEAJAAQAJAAAFgEQAGgEADgFQAEgHACgHIACgQIgCgQQgCgHgEgFQgDgFgGgFQgFgDgJAAQgJAAgFADgApWBZQgMgGgHgKQgHgJgEgNQgEgOAAgNQAAgMAEgNQAEgNAHgJQAIgKALgFQAKgGAPAAQALAAALAFQALAGAGAJIAAAAIAAhDIAlAAIAAC3IgjAAIAAgRIAAAAQgHAKgKAFQgKAFgNAAQgOAAgMgGgApDgNQgGAEgEAGQgDAEgCAIQgCAHAAAJIACAQQACAHAEAGQAFAHAFADQAGAEAJAAQAJAAAFgEQAHgEAEgGQADgHABgGQACgIAAgIQAAgIgCgIQgBgHgEgFQgDgGgHgEQgHgDgHAAQgIAAgIADgArqBbQgJgEgGgHQgFgHgDgKQgBgJAAgNIAAhRIAkAAIAABKQAAAQAFAIQAFAIANAAQAPAAAHgIQAHgKAAgUIAAhEIAkAAIAACEIgjAAIAAgTIAAAAQgHAMgLAFQgLAFgMAAQgPAAgJgEgAt0BaQgMgFgJgJQgJgJgFgNQgFgMABgRQgBgPAFgMQAFgNAJgKQAJgIAMgGQAOgFAPAAQAOAAAOAFQAOAGAIAIQAJAKAEANQAGALgBAQQABARgGAMQgEAMgJAKQgIAJgOAFQgNAFgPAAQgPAAgOgFgAtmgMQgHAEgDAFQgEAFgCAIQgBAHAAAIQAAAIABAIQACAIAEAFQACAGAIAEQAFAEAKAAQAJAAAGgEQAIgEACgGQAEgFACgIQABgIAAgIQAAgIgBgHQgCgIgEgFQgDgFgHgEQgGgEgJAAQgJAAgGAEgARpBcIAAi3IAkAAIAAC3gAMXBcIAAiEIAkAAIAACEgALeBcIAAhLQAAgQgGgIQgEgIgOAAQgOAAgHAJQgHAHAAAVIAABGIgkAAIAAiEIAiAAIAAASIABAAQAHgLALgFQAMgGALAAQANAAALAEQAJAEAFAHQAGAIACAKQADALgBAKIAABSgAJNBcIAAiEIAkAAIAACEgAISBcIAAi3IAkAAIAAC3gAvRBcIAAi3IAlAAIAAC3gAneAlIAAgfIBOAAIAAAfgAMXg9IAAgeIAkAAIAAAegAJNg9IAAgeIAkAAIAAAeg");
	this.shape_5.setTransform(-47.9283,-29.7865,1.0667,1.0667);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-172.3,-40.1,344.6,82.9);


(lib.soundwave3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1A6B96").s().p("AiPFxQCjiaAAjXQAAjYijiYIBXhSQDIC6AAEIQAAEIjIC7g");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.soundwave3, new cjs.Rectangle(-14.4,-45.1,28.8,90.30000000000001), null);


(lib.soundwave2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1A6B96").s().p("AhrDQQBdhVAAh6QAAh5hdhWIBZhTQB+B4AACpQAACqh+B4g");
	this.shape.setTransform(-0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.soundwave2, new cjs.Rectangle(-10.8,-29,21.6,58.1), null);


(lib.soundwave1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1A6B96").s().p("AhGAsQASgTAAgZQAAgZgSgSIBWhVQA3A2AABKQAABMg3A1g");
	this.shape.setTransform(-0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.soundwave1, new cjs.Rectangle(-7.1,-12.8,14.2,25.700000000000003), null);


(lib.sheen = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.486,1],-17.1,-7.9,17.1,8).s().p("AllFDIF1skIFWCfIl1Mkg");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.sheen, new cjs.Rectangle(-35.8,-48.2,71.6,96.5), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgIAJQgEgEAAgFQAAgEAEgEQAEgDAEgBQAFABAEADQAEAEAAAEQAAAFgEAEQgEADgFABQgEgBgEgDgAgGgGQgDADAAADQAAAFADADQADADADAAQAEAAADgDQADgDAAgFQAAgDgDgDQgDgEgEAAQgDAAgDAEgAAEAHIgEgGIgCAAIAAAGIgCAAIAAgNIAFAAQAFgBAAAFQAAACgEABIAEAGgAgCAAIACAAQABAAABAAQAAAAABAAQAAAAAAgBQABAAAAgBQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAIgCAAg");
	this.shape.setTransform(-21.625,10.55);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgqA8IAAh3IBRAAIAAAYIg2AAIAAAXIAzAAIAAAXIgzAAIAAAZIA6AAIAAAYg");
	this.shape_1.setTransform(61.5,-0.125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgjAuQgSgSAAgcQAAgcASgRQASgRAcAAQAbAAANARIgUARQgIgKgPAAQgOAAgKALQgKALAAAQQAAARAKALQAKALANAAQAQAAAJgNIAWAQQgOAVgdAAQgcAAgSgRg");
	this.shape_2.setTransform(48.875,-0.125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgdgFIgBAAIAABBIgaAAIAAh9IBWBHIAAAAIAAhBIAbAAIAAB9g");
	this.shape_3.setTransform(34.65,-0.15);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAhA8IgIgUIgyAAIgIAUIgdAAIA0h3IAVAAIA0B3gAAQARIgQgpIgQApIAgAAg");
	this.shape_4.setTransform(19.925,-0.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AglAwQgNgOAAgWIAAhJIAbAAIAABIQAAALAHAIQAHAHAJAAQALAAAHgHQAGgIAAgLIAAhIIAbAAIAABJQAAAWgNAOQgOAOgYAAQgXAAgOgOg");
	this.shape_5.setTransform(6.675,0.025);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgmgNIAABSIgcAAIAAiPIBpBYIAAhSIAcAAIAACPg");
	this.shape_6.setTransform(-9.125,-1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("ABAA/QhIAAg9g0QgTgPgPgTIgMgQIAAgFIAnAYQAtAWAfAAIAAhAIBkAAQAHAAAEAEQAFAEAAAGIAABhQAAAFgFAFQgEAEgHAAg");
	this.shape_7.setTransform(-37.075,5.575);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AhjA+QgHAAgEgEQgEgDgBgGIAAhhQABgFAEgFQAEgDAHAAIAkAAQBHAAA+AzQAeAZAQAZIAAAFQgQgMgXgLQgtgYggAAIAABAg");
	this.shape_8.setTransform(-54.15,-5.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65.7,-11.8,131.5,23.700000000000003);


(lib.head = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1A6B96").s().p("Al/H9IAAjgQiOhtg3iCQgcg/gMhOQgFgbgBguQgCgpABgfQAIh2AihaQAjhbBDhJQB7iGCnghQArgKBkAAIAMAAQBpAFBPAeQBNAdBNA+QCWB8AwCxQAPA+ACAyIACAlQAhA1AqBMIAOAeQAJASAEAOQAJAYAAAiQgBAkgUAcQgUAcgiANIgnASIAACiQAAAjgMAbQgWA4g4AYQglAQgnABIiQAAIAAE2gAisqiQiDAZhkBvQg2A5gcBLQgbBJgGBhQgBAaABAlQABAoAEAWQAKBAAXAzQAuBuCFBgQAbAUAAAiIAACxIFyCvIAAj1ID8AAQARAAAPgGQAOgHAIgOQADgHAAgQIAAjlIAfgPQApgVAlgRQAEgBABgBIABgEIgDgWQgDgJgSgjQgrhPgjg0QgKgSAAgUIAAgBQAAgcgBgOQgCgogMgwQgThKgog8Qgog8hAg1Qg+gzg9gWQg9gXhZgEIgHAAQhVAAglAGg");
	this.shape.setTransform(0.0179,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-62.8,-79,125.69999999999999,158);


(lib.hand = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgICAIgPAAIgKgmIgSAAIgHgpIgTAAIgHghIgUAAIgEgQIgTAAIgHglIAggBIAGATIASAAIADARIAUgBIgtiwIAfAAIAjCOIARgBIgPhAIAdAAIARBDIAPAAIgMgwIAdAAIASBBIARgBIgQgwIAQAAIAGAQIANAAIAjBtIgOAGIAOAxIgNAIIANAyIiDAJg");
	this.shape.setTransform(0.775,-0.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgpCJIgOAAIgLgmIgQAAIgIglIgTAAIgIgjIgSAAIgCgTIgTAAIgLg0IASgWIAuAAIgZhnIASgZIAEAAIAJgOIAfADIAEARIAQAAIAQA7IAeADIAEAOIAuACIAEARIAegBIAFARIAMAAIAGARIAQAAIAkBzIgLAIIANAtIgMAIIATA9IgbAQIikAQg");
	this.shape_1.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-16.8,-20.9,33.7,41.8);


(lib.dragon_med_one_logo = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#78C9C5").s().p("AguBxQgVgHgQgSQgPgQgJgWQgIgWAAgbQAAgbAJgVQAIgWAQgRQAPgQAWgKQAXgJAZgBQAdAAAXAMQAWANAOASQAOAUAGAYQAGAZgBAaIinAAQABAeAPAPQAPAOAZAAQATAAAOgKQAOgKADgKIA5AAQgOAqgcARQgbATgogBQgaABgXgKgAgXhEQgLAFgGAIQgGAIgCAIIgDAQIBnAAQgFgZgLgMQgLgNgYAAQgPAAgJAFg");
	this.shape.setTransform(227.4581,5.6624,1.1253,1.1253);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#78C9C5").s().p("AAtB4IAAiDQAAgdgJgOQgKgOgVAAQgZAAgNAPQgLARAAAiIAAB6IhAAAIAAjoIA9AAIAAAgIABAAQAMgSATgLQASgKAVAAQAwAAAUAbQARAWAAAwIAACOg");
	this.shape_1.setTransform(199.7473,5.3255,1.1253,1.1253);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#78C9C5").s().p("AhzB4QgqgvAAhHQAAhJAqgvQAsgxBHAAQBJAAArAxQAqAvAABJQAABHgqAvQgsAwhIAAQhHAAgsgwgAhDhKQgUAeABAuQgBAtAUAdQAYAhArAAQAsAAAYghQATgdAAgtQAAgugTgeQgYgigsAAQgrAAgYAig");
	this.shape_2.setTransform(166.7754,0.6835,1.1253,1.1253);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#2C2526").s().p("AgfChIAAlAIA/AAIAAFAg");
	this.shape_3.setTransform(130.2588,0.7116,1.1253,1.1253);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#2C2526").s().p("AhZBqQgXgTAAgiQgBgkAZgRQATgMAkgFIAzgHQAYgGAAgRQAAgTgNgHQgJgGgUAAQgmAAgDAjIhAAAQADgpAhgUQAdgRAsAAQBlAAABBDIAAB4QgBAnAJAMIhBAAQgFgNAAgJQgbAdgyAAQgjAAgVgRgAASALIgcAFQgSAEgJAGQgLAIAAAQQAAAeAnAAQAyAAABg2IAAgXQgIAFgQADg");
	this.shape_4.setTransform(110.7345,5.6912,1.1253,1.1253);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#2C2526").s().p("AhRBZQghghAAg1QAAg3AfgiQAggkA3AAQAsAAAeAWQAgAYADArIg+AAQgGgogpAAQgbAAgPAZQgMAUAAAdQAAAeAMATQAOAZAaAAQAWAAANgNQANgNADgWIA+AAQgGAugeAZQgeAZguAAQg0AAgggig");
	this.shape_5.setTransform(83.8675,5.6912,1.1253,1.1253);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#2C2526").s().p("AgfChIAAjoIA/AAIAADogAgfhrIAAg0IA/AAIAAA0g");
	this.shape_6.setTransform(64.2587,0.7116,1.1253,1.1253);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#2C2526").s().p("AhcB+QgagjABg0QgBgxAagiQAdglAxAAQAUAAASAJQATAJALARIABAAIAAh1IBAAAIAAFAIg+AAIAAgdIAAAAQgWAkgwAAQgxAAgegmgAgpgJQgMASAAAgQAAAeANAVQAPAYAbAAQAdAAAPgYQALgTAAghQAAgfgMgTQgOgWgdAAQgcAAgPAXg");
	this.shape_7.setTransform(43.4403,1.0774,1.1253,1.1253);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#2C2526").s().p("AhTBZQgggiAAg3QAAg0AhgiQAigkAzAAQA5AAAfArQAcAngDA4IinAAQACA7A2AAQASAAAQgKQAOgJADgMIA4AAQgaBPhTAAQg1AAghgigAgng3QgLANgBASIBnAAQgEgZgMgMQgMgMgXAAQgaAAgOASg");
	this.shape_8.setTransform(15.6946,5.6912,1.1253,1.1253);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#2C2526").s().p("ABrChIAAjjIgBAAIhODjIg2AAIhPjhIgBAAIAADhIhCAAIAAlAIBjAAIBLDbIABAAIBHjbIBjAAIAAFAg");
	this.shape_9.setTransform(-20.084,0.7116,1.1253,1.1253);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#2C2526").s().p("AAtB4IAAiDQAAgdgJgOQgKgOgWAAQgZAAgLAPQgMARAAAiIAAB6IhAAAIAAjoIA9AAIAAAgIABAAQAMgSAUgLQARgKAVAAQAwAAAUAbQARAWAAAwIAACOg");
	this.shape_10.setTransform(-68.4447,5.3255,1.1253,1.1253);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#2C2526").s().p("AhXBZQggghAAg4QAAg2AggiQAhgiA2AAQA3AAAhAiQAgAiAAA2QAAA4ggAhQghAig3AAQg2AAghgigAgsgyQgMATAAAfQAAAgAMATQAPAYAdAAQAeAAAOgYQAMgTAAggQAAgfgMgTQgOgXgeAAQgdAAgPAXg");
	this.shape_11.setTransform(-97.1403,5.6912,1.1253,1.1253);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#2C2526").s().p("AhHCSQghgUgDglIA/AAQAIAgAnAAQAaAAAOgQQAMgPgBgbIAAgeIAAAAQgKARgTAKQgTAJgVAAQgyAAgagjQgXgfgBgyQABgwAZghQAcgjAuAAQAwAAAVAmIAAAAIAAgfIA+AAIAADYQgBApgTAZQgfAmhFAAQgnAAgcgSgAgmheQgNASAAAcQAAAdAMASQAOAVAZAAQAaAAAPgTQANgRAAgbQAAgggLgSQgOgVgdAAQgYAAgOAUg");
	this.shape_12.setTransform(-126.8769,10.305,1.1253,1.1253);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#2C2526").s().p("AhZBqQgXgTAAgiQAAgkAYgRQASgMAlgFIAzgHQAXgGAAgRQAAgTgMgHQgJgGgUAAQgmAAgDAjIhAAAQACgpAigUQAcgRAsAAQBmAAAABDIAAB4QAAAlAIAOIhAAAQgEgKgBgMQgbAdgyAAQgjAAgVgRgAASALIgdAFQgSAEgIAGQgLAIAAAQQAAAeAnAAQAyAAAAg2IAAgXQgGAFgRADg");
	this.shape_13.setTransform(-154.7567,5.6912,1.1253,1.1253);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#2C2526").s().p("AhKB4IAAjoIA9AAIAAArIAAAAQAKgWATgNQAVgOAYgBQAHABAHACIAAA8QgKgDgNAAQghAAgQAWQgNAUAAAgIAABpg");
	this.shape_14.setTransform(-175.9409,5.3255,1.1253,1.1253);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#2C2526").s().p("AiNChIAAlAICLAAQBAAAAnAnQApAqAABNQAABIgkArQgmAvhGAAgAhGBlIA/AAQAhAAAVgVQAZgaAAgxQAAgzgUgZQgXgdgxgBIgyAAg");
	this.shape_15.setTransform(-203.4268,0.7116,1.1253,1.1253);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#636666").s().p("AgQApQgJgDgGgGQgGgGgEgIQgDgIAAgKQAAgJADgIQAEgJAGgFQAHgHAIgCQAHgEAJAAQAKAAAIAEQAHACAHAHQAFAFAEAJQAEAIAAAJQAAAKgEAIQgDAIgGAGQgHAGgHADQgIAEgKAAQgJAAgHgEgAgOgiQgGADgFAFQgGAGgCAGQgDAHAAAHQAAAIADAHQACAGAGAGQAFAFAGADQAIADAGAAQAIAAAGgDQAHgDAGgFQAEgFADgHQADgHAAgIQAAgHgDgHQgDgHgEgFQgGgFgHgDQgGgDgIAAQgGAAgIADgAANAaIgNgWIgIAAIAAAWIgIAAIAAgzIATAAQAJAAAFADQAEAEAAAIQAAAHgEADQgEADgFAAIAOAXgAgIgCIAMAAIAFgBIADgDIABgFIgBgEIgCgCIgIgCIgKAAg");
	this.shape_16.setTransform(-240.1404,-13.0454,1.1253,1.1253);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#636666").s().p("AgrBwQgVgIgOgRQgOgQgHgWQgHgZgBgYQAAgZAIgXQAJgXAOgPQAOgQAVgKQAUgJAXAAQAfABAUANQAUAMANAUQANAVAEAWQAFAZgBATIitAAQAAAQADANQAFAOAJAKQAJAMANAFQAQAHAQgBQAYABAQgMQAPgLAGgXIAlAAQgHAngaAUQgaATgoAAQgbABgUgKgAgahSQgNAGgIAIQgIAKgFALQgFANgBANICFAAQgCgOgFgMQgDgJgKgMQgJgIgMgGQgMgEgOAAQgPAAgLAEg");
	this.shape_17.setTransform(-256.9049,5.6631,1.1253,1.1253);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#636666").s().p("AgrBxQgUgIgOgRQgOgQgHgVQgHgVAAgbQAAgaAHgVQAGgXAOgRQAOgRAVgKQAVgKAaAAQAUAAARAGQAQADAPALQANAKAIAPQAJAOACAWIgnAAQgFgXgOgMQgOgMgZABQgTAAgPAHQgNAIgJAMQgIAMgEARQgDAQAAARQAAASADANQAEAQAIAMQAJANAMAGQAOAIAQgBQAdAAAQgOQAQgPADgcIAoAAQgHAsgaAXQgZAYgtgBQgZAAgVgIg");
	this.shape_18.setTransform(-282.5369,5.6631,1.1253,1.1253);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#636666").s().p("AA6B3IAAicQAAgVgNgNQgMgNgWAAQgSAAgMAFQgNAGgIAKQgIAIgFAOQgEAOAAAPIAACDIgmAAIAAjoIAkAAIAAAlIABAAQAXgqAzAAQAYAAAOAGQAPAGAKAMQAKAMADAOQAEAOAAAVIAACYg");
	this.shape_19.setTransform(-308.588,5.3817,1.1253,1.1253);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#636666").s().p("AA6BxQgIgJAAgSQgQASgVAJQgTAIgZAAQgRAAgNgDQgPgEgKgIQgKgHgGgNQgGgMAAgRQAAgUAGgNQAHgNALgHQALgHAOgEIAdgHIAegFQAOgBAKgDQALgDAGgGQAHgGAAgKQAAgMgFgIQgFgJgHgDQgIgEgJgCIgRAAQgYgBgQAKQgRAJgBAaIgmAAQABgWAIgPQAIgPANgJQAMgJATgEQATgFASAAQANABASACQAPACANAHQAMAGAIAOQAIAMAAAUIAAB3QAAANABAHQACAGAJAAIALgCIAAAdQgJAHgSgBQgPAAgJgIgAAcAEIgxAIQgNADgKAEQgLAEgGAIQgHAIAAAPQAAAJAEAGQAEAIAGADQAHAFAHABIARACQATAAANgFQANgGAJgIQAJgIADgJQAEgJAAgHIAAgnQgGAFgNACg");
	this.shape_20.setTransform(-334.0203,5.6631,1.1253,1.1253);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#636666").s().p("Ag1BxQgPgGgKgMQgKgLgDgPQgEgRAAgSIAAiYIAmAAIAACdQAAAWANAMQANANAVAAQAQAAAOgGQAMgGAJgJQAJgLAEgMQAEgOAAgPIAAiDIAmAAIAADoIgkAAIAAglIAAAAQgNAWgSAKQgUAKgYAAQgXAAgPgGg");
	this.shape_21.setTransform(-360.4653,5.9725,1.1253,1.1253);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#636666").s().p("ABRChIinkBIgBAAIAAEBIgoAAIAAlAIAuAAICnEDIABAAIAAkDIApAAIAAFAg");
	this.shape_22.setTransform(-391.0459,0.7116,1.1253,1.1253);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AAfAeIAAggQAAgSgMAAQgKAAgDAJIgBAGIAAAjIgJAAIAAgiQAAgQgMAAQgKAAgDAKIgBAFIAAAjIgKAAIgBg6IAJAAIABAKIAAAAQAGgLAMAAQANAAADAMIAAAAQACgEAFgEQAFgEAHAAQAIAAAFAFQAHAHAAANIAAAig");
	this.shape_23.setTransform(-271.0583,103.2613,1.3652,1.3652);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgTAWQgIgIAAgOQAAgNAIgIQAIgIALAAQANAAAIAIQAHAIAAANQAAAOgJAJQgIAHgLAAQgMAAgHgIgAgMgOQgFAGAAAIQAAAKAFAGQAFAGAHAAQAHAAAFgGQAFgHAAgJQAAgIgEgGQgEgHgJAAQgHAAgFAHg");
	this.shape_24.setTransform(-282.3899,103.3295,1.3652,1.3652);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgOAWQgIgIAAgNQAAgNAJgIQAIgJANAAQAJAAAGADIgDAIQgEgDgIAAQgJAAgFAHQgFAGAAAIQAAAKAFAGQAGAGAIAAQAHAAAGgDIACAIQgHADgKAAQgMAAgIgIg");
	this.shape_25.setTransform(-290.3766,103.3295,1.3652,1.3652);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgGAAQAAgHAGAAQAHAAAAAHQAAAHgHAAQgGAAAAgHg");
	this.shape_26.setTransform(-295.701,106.4355,1.3652,1.3652);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgRAWQgIgIABgNQAAgNAGgIQAIgJAMAAQAMAAAHAJQAEAIAAAKIAAAEIgnAAQAAAUASAAQAIAAAJgDIABAIQgIADgLAAQgMAAgIgIgAgOgFIAdAAQABgRgPAAQgNAAgCARg");
	this.shape_27.setTransform(-301.4009,103.3295,1.3652,1.3652);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgOAWQgIgIAAgNQAAgNAJgIQAIgJANAAQAJAAAGADIgCAIQgFgDgIAAQgJAAgFAHQgFAGAAAIQAAAKAGAGQAFAGAIAAQAHAAAGgDIACAIQgHADgKAAQgMAAgIgIg");
	this.shape_28.setTransform(-309.0463,103.3295,1.3652,1.3652);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AAOAeIAAghQAAgRgNAAQgKAAgDALIgBAFIAAAiIgKAAIgBg6IAJAAIABAKQAGgLAMAAQAVAAAAAZIAAAig");
	this.shape_29.setTransform(-317.3402,103.2613,1.3652,1.3652);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgRAZQgFgEAAgHQAAgWAiABIAAgBQAAgOgMAAQgIAAgIAFIgCgHQAJgFAJAAQAWAAAAAXIABAjIgKAAIAAgHIgBAAQgGAIgLAAQgHAAgFgFgAgLAMQAAALAKAAQAJAAADgKIABgEIAAgJQgXAAAAAMg");
	this.shape_30.setTransform(-326.0437,103.3295,1.3652,1.3652);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgYAEIAAghIALAAIAAAgQAAASANAAQAJAAAEgKIABgFIAAgjIAKAAIABA6IgKAAIAAgKIgBAAQgGALgMAAQgUAAAAgag");
	this.shape_31.setTransform(-334.2693,103.3978,1.3652,1.3652);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAOAeIAAghQAAgRgNAAQgKAAgDALIgBAFIAAAiIgKAAIgBg6IAJAAIABAKIAAAAQAGgLAMAAQAIAAAGAFQAHAGAAAOIAAAig");
	this.shape_32.setTransform(-343.3482,103.2613,1.3652,1.3652);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgGAAQAAgHAGAAQAHAAAAAHQAAAHgHAAQgGAAAAgHg");
	this.shape_33.setTransform(-349.4577,106.4355,1.3652,1.3652);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgSAZQgEgEAAgHQAAgWAiABIAAgBQAAgOgNAAQgIAAgHAFIgCgHQAIgFAKAAQAWAAAAAXIAAAVIABAOIgKAAIAAgHIgBAAQgFAIgLAAQgJAAgFgFgAgMAMQAAALAKAAQAKAAADgKIABgEIAAgJQgYAAAAAMg");
	this.shape_34.setTransform(-355.4307,103.3295,1.3652,1.3652);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgEApIAAg6IAJAAIAAA6gAgGghQAAgGAGgBQAHABAAAGQAAAHgHgBQgGABAAgHg");
	this.shape_35.setTransform(-361.0965,101.7936,1.3652,1.3652);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgEArIAAhVIAJAAIAABVg");
	this.shape_36.setTransform(-364.9875,101.4864,1.3652,1.3652);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgRAZQgFgEAAgHQAAgLAJgEQAJgGAPAAIAAgBQABgOgMAAQgIAAgIAFIgCgHQAJgFAJAAQAWAAAAAXIABAjIgKAAIgBgHQgGAIgLAAQgHAAgFgFgAgMAMQAAALALAAQAIAAAEgKIABgEIAAgJQgYAAAAAMg");
	this.shape_37.setTransform(-371.0287,103.3295,1.3652,1.3652);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgNAeIgBg6IAKAAIAAAMIABAAQADgNAMAAIADAAIAAAKIgEAAQgLAAgCAOIgBAFIAAAeg");
	this.shape_38.setTransform(-376.9334,103.2613,1.3652,1.3652);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgDAgQgEgEAAgLIAAgfIgJAAIAAgIIAJAAIAAgLIAJgCIAAANIAPAAIAAAIIgPAAIAAAfQAAALAIAAIAGgBIAAAIQgDACgGgBQgHAAgDgEg");
	this.shape_39.setTransform(-382.804,102.4762,1.3652,1.3652);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgSAaIACgIQAHAEAIAAQAJAAABgIQAAgHgKgEQgQgFAAgKQABgIAFgEQAGgFAHAAQAJAAAGADIgDAIQgEgDgIAAQgJAAAAAHQABAGAJAEQAQAFAAAMQAAARgVAAQgKAAgGgEg");
	this.shape_40.setTransform(-388.7087,103.3295,1.3652,1.3652);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgYAEIAAghIALAAIAAAgQAAASANAAQAJAAAEgKIABgFIAAgjIAKAAIABA6IgKAAIAAgKIgBAAQgGALgMAAQgUAAAAgag");
	this.shape_41.setTransform(-396.4565,103.3978,1.3652,1.3652);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgSAZQgEgEAAgHQAAgWAiABIAAgBQAAgOgMAAQgJAAgHAFIgCgHQAJgFAJAAQAWAAABAXIAAAjIgJAAIgBgHIgBAAQgGAIgLAAQgIAAgFgFgAgLAMQAAALAKAAQAKAAACgKIABgEIAAgJQgXAAAAAMg");
	this.shape_42.setTransform(-405.1599,103.3295,1.3652,1.3652);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-408.3,-18.2,648.9,125.7);